fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    stdmod: "git://github.com/stdmod/stdmod.git"
    module_data: "https://github.com/ripienaar/puppet-module-data"
  symlinks:
    postgresql: "#{source_dir}"
