name          'example42-postgresql'
version       '0.0.5'
source        'UNKNOWN'
author        'example42'
license       'Apache License, Version 2.0'
summary       'This module installs and manages postgresql'
description   'This module installs and manages postgresql UNKNOWN. Based on stdmod/puppet-skeleton-standard 0.0.5'
project_page  'UNKNOWN'
dependency    'puppetlabs/stdlib'
dependency    'example42/stdmod'
dependency    'ripienaar/module_data'
