#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2006 Sun Microsystems, Inc. All rights reserved.
# Use is subject to license terms.
#
# ident "%Z%%M% %I% %E SMI"
. /lib/svc/share/smf_include.sh
# SMF_FMRI is the name of the target service. This allows multiple instances
# to use the same script.

getproparg() {
   val=`svcprop -p $1 $SMF_FMRI`
   [ -n "$val" ] && echo $val
}

PGBIN=/usr/bin
PGDATA=`getproparg postgresql/data`
PGLOG=`getproparg postgresql/log`

if [ -z $SMF_FMRI ]; then
   echo "SMF framework variables are not initialized."
   exit $SMF_EXIT_ERR
fi

if [ -z $PGDATA ]; then
   echo "postgresql/data property not set"
   exit $SMF_EXIT_ERR_CONFIG
fi

if [ -z $PGLOG ]; then
   echo "postgresql/log property not set"
   exit $SMF_EXIT_ERR_CONFIG
fi

case "$1" in
   'start')
      $PGBIN/pg_ctl -D $PGDATA -l $PGDATA/$PGLOG start
      ;;
   'stop')
      $PGBIN/pg_ctl -D $PGDATA stop
      ;;
   'refresh')
      $PGBIN/pg_ctl -D $PGDATA reload
      ;;
   *)
      echo $"Usage: $0 {start|refresh}"
      exit 1
      ;;
esac

exit $SMF_EXIT_OK
